[default]
dynaconf_include = ["app/config/*.toml"]

### Deafult configurations
APP_NAME='Falafel'
SECRET_KEY=''
APP_URL='http://localhost'
ENV='@format {env[FLASK_ENV]}'

#### Database
DB_CONNECTION='mysql+pymysql'
DB_HOST='localhost'
DB_PORT='3306'
DB_DATABASE='umbaweb'
DB_USERNAME='root'
DB_PASSWORD=''

### Mail 
MAIL_MAILER='smtp'
MAIL_HOST='smtp.mailtrap.io'
MAIL_PORT='2525'
MAIL_USERNAME='null'
MAIL_PASSWORD='null'
MAIL_ENCRYPTION='null'
MAIL_FROM_ADDRESS='null'
MAIL_FROM_NAME='@format {this.APP_NAME}'
