table_name = 'countries'
action = 'create'
[create]
    [create.id]
    primary_key = "True"
    type = "Integer"

    [create.code]
    type = "String"
    length = "2"
    nullable = "False"

    [create.name]
    type = "String"
    nullable = "False"

    [create.phone_code]
    type = "String"
    length = "4"

    [create.code_iso]
    type = "String"
    length = "3"

    [crate.active]
    type = "Boolean"
    default = "True"

    [create.created_at]
    default = "datetime.utcnow"
    nullable = "False"
    type = "TIMESTAMP"

    [create.updated_at]
    nullable = "False"
    onupdate = "datetime.utcnow"
    type = "TIMESTAMP"
